### ISSUE TITLE
Plugins and Settings folder discrepancy

### ISSUE THREAD

**Issue by hlaueriksson** [KawaiiZapic/PowertoysRunTOTP#1]
The folder in the release zip file is `TOTP`, but the settings file is generated under the folder `Zapic.Plugin.TOTP`.
It would be nice it the two matched.

**Comment by KawaiiZapic** [comment]
> The folder in the release zip file is `TOTP`, but the settings file is generated under the folder `Zapic.Plugin.TOTP`. It would be nice it the two matched.

That's a good idea, thanks for your advice, I will change it to `TOTP.json` ASAP 😉

**Comment by KawaiiZapic** [comment]
Hello, I just want to let you know that the settings directory now has the same name as the plugin in [1.1.0](https://github.com/KawaiiZapic/PowertoysRunTOTP/releases/tag/1.1.0) (Plugin will do auto migration, so you don't need to do anything other than download new version of plugin). I also introduce local encryption in this version.
Please feel free to re-open the issue if there are any questions or create a new one if there is a new question.

**Comment by hlaueriksson** [comment]
Hi @KawaiiZapic

I think my advice in this issue was wrong. Sorry for the trouble caused.

The consensus seems to be:
> The plugin folder should have the same name as the plugin.

I created this proposal for a community plugin checklist:
- https://github.com/hlaueriksson/awesome-powertoys-run-plugins/pull/17/files

You are welcome to review and give feedback. Thanks!

**Comment by KawaiiZapic** [comment]
> Hi @KawaiiZapic
> 
> I think my advice in this issue was wrong. Sorry for the trouble caused.
> 
> The consensus seems to be:
> 
> > The plugin folder should have the same name as the plugin.
> 
> I created this proposal for a community plugin checklist:
> 
> * https://github.com/hlaueriksson/awesome-powertoys-run-plugins/pull/17/files
> 
> You are welcome to review and give feedback. Thanks!

I see, but I have more question about this part of proposal, let's discuss this in the [hlaueriksson/awesome-powertoys-run-plugins#17](hlaueriksson/awesome-powertoys-run-plugins#17)

EDIT(1/26 21:12 GMT+8): @hlaueriksson 
I read the checklist again, and from `1.2.2`, I used `PluginsStorage<T>` as my config file handler, so the checklist looks good to me. Thank you for your mention.
