### ISSUE TITLE
Crash after pasting authenticator URL

### ISSUE THREAD

**Issue by LSTANCZYK** [KawaiiZapic/PowertoysRunTOTP#3]
When i try to paste the authenticator url it initially is recognized correctly and shows a prompt to import items:
![image](https://github.com/KawaiiZapic/PowertoysRunTOTP/assets/2145721/e327d46a-6dca-4ca5-a190-0f6b6fd98fd8)

When I confirm the import Power toys crash: 
![image](https://github.com/KawaiiZapic/PowertoysRunTOTP/assets/2145721/d19ec677-abb1-47c0-9ef6-c3d04a3f459d)

I have noticed that the json config file stays at 0 bytes 
![image](https://github.com/KawaiiZapic/PowertoysRunTOTP/assets/2145721/4983411a-5f33-4cec-aab5-fbfc497c047f)

In my attempt to troubleshoot I deleted the config file and attempted the setup again. This time it did not crush, but the config file was again created with 0 length. When i entered '[' I got the following message: 

![image](https://github.com/KawaiiZapic/PowertoysRunTOTP/assets/2145721/7e74a0da-2703-4a0c-b37f-c88a2148e5f1)

Is there any more information you need to help troubleshoot this?

**Comment by KawaiiZapic** [comment]
Thanks for your feedback! This plugin is poorly tested after so much breaking changes were made in PT, I'm so grateful for you testing.  
I'll take a look at tomorrow morning(GMT+8) and try to find out what's happening.  

May I know what version of Powertoys you are using? This help a lot for me to reproduce the problem.

**Comment by LSTANCZYK** [comment]
I am using 0.76.2

**Comment by KawaiiZapic** [comment]
I have fixed this problem and test in my machine, it should be work now.

https://github.com/KawaiiZapic/PowertoysRunTOTP/releases/tag/1.2.2

**Comment by KawaiiZapic** [comment]
@LSTANCZYK Hello, last time I hearing from you is 5 days ago, I'd like to know is the new version of TOTP plugin solved your crash problem or not. If it does not solve any problem or there are some new problems (better not), please let me know.

**Comment by LSTANCZYK** [comment]
My apologies for the delay. I will try to check on it today and let you
know.

**Comment by LSTANCZYK** [comment]
I was just now able to verify. Everything worked perfect! Thank you!

**Comment by LSTANCZYK** [comment]
Closing the issue
