### ISSUE TITLE
Lose data after update

### ISSUE THREAD

**Issue by LambdaSoft** [KawaiiZapic/PowertoysRunTOTP#4]
After updating PowerToys to the latest version (0.78), the plugin has lost all data (OTPList is empty)

**Comment by KawaiiZapic** [comment]
I'm sorry about that. Can you provide more info about this? Such as what version you're from and what version you have been upgraded to.  
And check `%LocalAppData%l\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Community.PowerToys.Run.Plugin.TOTP` to find if any data remain there.  
I'll try to reproduce your problem and find out what happended

**Comment by KawaiiZapic** [comment]
This is a upstream bug from PT Run, I'm making a simple workaround to handle this.

**Comment by KawaiiZapic** [comment]
This problem has been fixed in [v1.2.3](https://github.com/KawaiiZapic/PowertoysRunTOTP/releases/tag/1.2.3), I make a quick workaround about this problem.  
I will report this as a bug to PowerToys, thank you for reporting this bug.

**Comment by LambdaSoft** [comment]
Thanks!

> This problem has been fixed in [v1.2.3](https://github.com/KawaiiZapic/PowertoysRunTOTP/releases/tag/1.2.3), I make a quick workaround about this problem. I will report this as a bug to PowerToys, thank you for reporting this bug.

Thanks to you for the fix!
