### ISSUE TITLE
Is there a way to use it with microsoft auth?

### ISSUE THREAD

**Issue by Daydreamer-riri** [KawaiiZapic/PowertoysRunTOTP#5]
Hi, this is a great plugin, but my auth client doesn't seem to support exporting OTPAuth URIs.
 I was wondering if there was a way I could use this plugin.

**Comment by KawaiiZapic** [comment]
Sorry, if your auth app doesn't not support export account locally, I can't import accounts from your app.

However, you can disable OTP and re-enable it(or re-create it), there will be a QR code for you to setup your auth app. You can scan the QR code for many times, that mean you can setup multiple auth apps before you end the setup step.
You can use a QR code scanner to scan the QR code to get the setup links. This plugin support standard otp setup link(otpauth://), you can paste it in PT Run search bar and plugin show you a option to add it. After add it to this plugin, you can use your favorite auth app to add it again.

Time-based OTP can have multiple instances for one account. You will get same code at same time both in this plugin and your auth app.

**Comment by Daydreamer-riri** [comment]
Thanks for your reply!
